project:
  type: website


execute:
  echo: false
  warning: false
  message: false
  execute-dir: project

website:
  title: "Construction et analyse de la base sur les élèves de l'ENSAI"

  navbar:
    background: "#700F5D"
    left:
      - text: "Présentation du projet"
        href: index.qmd
      - text: "Premières analyses"
        href: "scripts/analyses_2015_2024.qmd"
      - text: "Documentation"
        menu:
          - text: "Requêtes SQL"
            href: "scripts/requetes_SQL.qmd"
          - text: "Script R"
            href: "scripts/creation_BDD.qmd"
          - text: "Dictionnaire des variables"
            href: "scripts/dictionnaire.qmd"
    right:
      - text: "À propos"
        href: about.qmd

  # Sidebar (plan du site) à gauche
  sidebar:
    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - text: "Présentation du projet"
        file: index.qmd
      - text: "Premières analyses"
        file: "scripts/analyses_2015_2024.qmd"
      - section: "Documentation"
        contents:
          - text: "Requêtes SQL"
            file: "scripts/requetes_SQL.qmd"
          - text: "Script R"
            file: "scripts/creation_BDD.qmd"
          - text: "Dictionnaire des variables"
            file: "scripts/dictionnaire.qmd"

format:
  html:
    theme:
      light: cosmo
      dark: solar
    css: styles.css
    toc: true
    toc-location: left
    toc-depth: 3
