project:
  type: website

website:
  title: "Analyse BDD élèves"

  navbar:
    background: "#700F5D"

    left:
      # 1) page d’accueil
      - text: "Présentation du projet"
        href: index.qmd

      # 2) Premières analyses
      - text: "Premières analyses"
        href: doc/Premières analyses.qmd   

      # 3) Requete SQL
      - text: "Requête SQL"
        href: doc/Requête SQL.qmd   

      # 4) entrée avec un sous-menu
      - text: "Code R"
        href: doc/Code R.qmd  

    right:
      - text: "À propos"
      - href: about.qmd         

format:
  html:
    theme:
      light: cosmo
      dark:  solar
    css:   styles.css
