name: Render and Publish

on:
  push:
    branches: [ main ]   # déclenche sur push vers main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Récupère ton code
      - uses: actions/checkout@v4

      # 2. Installe R
      - uses: r-lib/actions/setup-r@v2

      # 3. Cache les packages R
      - name: Cache R packages
        uses: actions/cache@v4
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-r-${{ hashFiles('**/DESCRIPTION') }}
          restore-keys: ${{ runner.os }}-r-

      # 4. Installe Quarto
      - uses: quarto-dev/quarto-actions/setup@v2

      # 5. Installe les packages R nécessaires
      - name: Install R packages
        run: |
          Rscript -e 'install.packages(c("dplyr","ggplot2","readr","tidyr","forcats","arrow","scales","knitr","kableExtra","readxl","DT"))'

      # 6. Compile le site
      - name: Render site
        run: quarto render

      # 7. Déploie sur GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
