name: Render and Deploy Quarto Site

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Récupérer le dépôt
      - uses: actions/checkout@v4

      # 2. Installer Quarto
      - uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: "1.4.554"   # adapte à ta version locale

      # 3. Installer R
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: "4.3.2"   # adapte à ta version locale

      # 4. Installer dépendances système (GDAL, GEOS, PROJ, etc.)
      - name: Install system dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y \
            make \
            cmake \
            gdal-bin \
            libgdal-dev \
            libproj-dev \
            libudunits2-dev \
            libgeos-dev \
            libpng-dev \
            pandoc

      # 5. Mettre en cache les packages R (accélère les builds)
      - name: Cache R packages
        uses: actions/cache@v3
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-r-${{ hashFiles('**/renv.lock') }}
          restore-keys: ${{ runner.os }}-r-

      # 6. Installer renv et restaurer l’environnement
      - name: Restore R packages with renv
        run: |
          Rscript -e 'install.packages("renv", repos = "https://cloud.r-project.org")'
          Rscript -e 'renv::restore()'

      # 7. Rendre le site Quarto
      - name: Render Quarto Project
        run: quarto render

      # 8. Déployer sur GitHub Pages
      - uses: actions/upload-pages-artifact@v2
        with:
          path: _site

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write

    steps:
      - uses: actions/deploy-pages@v2
