name: Render and Publish

on:
  push:
    branches: [ main ]   # déclenche sur chaque push vers main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    env:
      RENV_PATHS_CACHE: ~/.cache/R/renv

    steps:
      # 1. Récupère ton code
      - uses: actions/checkout@v4

      # 2. Installe R
      - uses: r-lib/actions/setup-r@v2

      # 3. Installe les bibliothèques système nécessaires à terra, sf, rmarkdown, etc.
      - name: Install system libraries
        run: |
          sudo apt-get update -y
          sudo apt-get install -y \
            make \
            cmake \
            gdal-bin \
            libgdal-dev \
            libproj-dev \
            libudunits2-dev \
            libgeos-dev \
            libpng-dev \
            pandoc

      # 4. Cache des packages R (basé sur renv.lock)
      - name: Cache R packages
        uses: actions/cache@v4
        with:
          path: ${{ env.RENV_PATHS_CACHE }}
          key: ${{ runner.os }}-r-${{ hashFiles('**/renv.lock') }}
          restore-keys: ${{ runner.os }}-r-

      # 5. Installe Quarto
      - uses: quarto-dev/quarto-actions/setup@v2

      # 6. Restaure les packages R via renv
      - name: Restore R packages with renv
        run: Rscript -e "install.packages('renv', repos='https://cloud.r-project.org'); renv::restore(prompt = FALSE)"

      # 7. Compile le site avec Quarto
      - name: Render site
        run: quarto render

      # 8. Déploie le site sur GitHub Pages (branche gh-pages) avec peaceiris v4
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
